export const PHILIPPINE_REGIONS = [
  "National Capital Region (NCR)",
  "Ilocos Region (Region I)",
  "Cagayan Valley (Region II)",
  "Central Luzon (Region III)",
  "CALABARZON (Region IV-A)",
  "MIMAROPA (Region IV-B)",
  "Bicol Region (Region V)",
  "Western Visayas (Region VI)",
  "Central Visayas (Region VII)",
  "Eastern Visayas (Region VIII)",
  "Zamboanga Peninsula (Region IX)",
  "Northern Mindanao (Region X)",
  "Davao Region (Region XI)",
  "SOCCSKSARGEN (Region XII)",
  "Caraga (Region XIII)",
  "Cordillera Administrative Region (CAR)",
  "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)"
];

export const PHILIPPINE_REGIONS_SHORT = [
  "NCR",
  "Region I",
  "Region II",
  "Region III",
  "Region IV-A",
  "Region IV-B",
  "Region V",
  "Region VI",
  "Region VII",
  "Region VIII",
  "Region IX",
  "Region X",
  "Region XI",
  "Region XII",
  "Region XIII",
  "CAR",
  "BARMM"
];

export const REGION_DISPLAY_NAMES: Record<string, string> = {
  'CAR': 'CAR',
  'Region I': 'Region I (Ilocos Region)',
  'Region II': 'Region II (Cagayan Valley)',
  'Region III': 'Region III (Central Luzon)',
  'NCR': 'NCR',
  'Region IV-A': 'Region IV-A (CALABARZON)',
  'Region IV-B': 'Region IV-B (MIMAROPA)',
  'Region V': 'Region V (Bicol)',
  'Region VI': 'Region VI (Western Visayas)',
  'Region VII': 'Region VII (Central Visayas)',
  'Region VIII': 'Region VIII (Eastern Visayas)',
  'Region IX': 'Region IX (Zamboanga Peninsula)',
  'Region X': 'Region X (Northern Mindanao)',
  'Region XI': 'Region XI (Davao Region)',
  'Region XII': 'Region XII (SOCCSKSARGEN)',
  'Region XIII': 'CARAGA',
  'BARMM': 'BARMM',
};

export const REGISTRATION_REGIONS = [
  'CAR',
  'Region I',
  'Region II',
  'Region III',
  'NCR',
  'Region IV-A',
  'Region IV-B',
  'Region V',
  'Region VI',
  'Region VII',
  'Region VIII',
  'Region IX',
  'Region X',
  'Region XI',
  'Region XII',
  'Region XIII',
  'BARMM',
] as const;

export const REGISTRATION_OCCUPATIONS = [
  'Teacher I',
  'Teacher II',
  'Teacher III',
  'Master Teacher I',
  'Master Teacher II',
  'Head Teacher',
  'School Principal',
  'Division Office Staff',
  'Other Education Personnel',
] as const;

export const REGISTRATION_QUALIFICATION_LEVELS = [
  'Bachelor\'s Degree',
  'Bachelor\'s Degree with Units in MA/MS',
  'Master\'s Degree',
  'Doctoral Units',
  'Doctoral Degree',
  'Not Specified',
] as const;

export const REGISTRATION_GENDER_OPTIONS = [
  'Female',
  'Male',
  'Prefer not to say',
] as const;

export const REGISTRATION_AGE_BRACKETS = [
  'Below 25',
  '25-34',
  '35-44',
  '45-54',
  '55 and above',
  'Prefer not to say',
] as const;

export const STAR_PARTICIPATION_STATUSES = [
  'Not Yet Participated',
  'Interested',
  'Applied',
  'Active Participant',
  'Alumni',
] as const;

export const REGION_DIVISIONS_BY_REGION: Record<string, string[]> = {
  'CAR': [
    'Abra',
    'Apayao',
    'Baguio City',
    'Benguet',
    'Ifugao',
    'Kalinga',
    'Mountain Province',
    'Tabuk City',
  ],
  'Region I': [
    'Ilocos Norte',
    'Ilocos Sur',
    'La Union',
    'Pangasinan I',
    'Pangasinan II',
    'Alaminos City',
    'Batac City',
    'Candon City',
    'Dagupan City',
    'Laoag City',
    'San Carlos City',
    'San Fernando City',
    'Urdaneta City',
    'Vigan City',
  ],
  'Region II': [
    'Batanes',
    'Cagayan Province',
    'Isabela',
    'Nueva Vizcaya',
    'Quirino',
    'Cauayan City',
    'Ilagan City',
    'Santiago City',
    'Tuguegarao City',
  ],
  'Region III': [
    'Aurora',
    'Bataan',
    'Baliwag City',
    'Bulacan',
    'Nueva Ecija',
    'Pampanga',
    'Tarlac',
    'Zambales',
    'Angeles City',
    'Balanga City',
    'Cabanatuan City',
    'Gapan City',
    'Mabalacat City',
    'Malolos City',
    'Meycauayan City',
    'Olongapo City',
    'San Fernando City',
    'San Jose City',
    'San Jose Del Monte',
    'Science City of Muñoz',
    'Tarlac City',
  ],
  'NCR': [
    'Caloocan City',
    'Las Piñas City',
    'Makati City',
    'Malabon City',
    'Manila',
    'Marikina City',
    'Muntinlupa City',
    'Navotas City',
    'Parañaque City',
    'Pasay City',
    'Pasig City',
    'Quezon City',
    'San Juan City',
    'Taguig City-Pateros',
    'Valenzuela City',
  ],
  'Region IV-A': [
    'Batangas',
    'Cavite',
    'Laguna',
    'Quezon',
    'Rizal',
    'Antipolo City',
    'Bacoor City',
    'Batangas City',
    'Biñan City',
    'Cabuyao City',
    'Calamba City',
    'Cavite City',
    'Dasmariñas City',
    'Imus City',
    'Lipa City',
    'Lucena City',
    'San Pablo City',
    'Sta. Rosa City',
    'Tanauan City',
    'Tayabas City',
    'General Trias City',
    'San Pedro City',
    'Sto. Tomas City',
  ],
  'Region IV-B': [
    'Marinduque',
    'Occidental Mindoro',
    'Oriental Mindoro',
    'Palawan',
    'Romblon',
    'Calapan City',
    'Puerto Princesa',
  ],
  'Region V': [
    'Albay',
    'Camarines Norte',
    'Camarines Sur',
    'Catanduanes',
    'Masbate',
    'Sorsogon',
    'Iriga City',
    'Legazpi City',
    'Masbate City',
    'Naga City',
    'Sorsogon City',
    'Tabaco City',
  ],
  'Region VI': [
    'Aklan',
    'Antique',
    'Bacolod City',
    'Bago City',
    'Cadiz City',
    'Capiz',
    'Escalante City',
    'Guimaras',
    'Himamaylan City',
    'Iloilo',
    'Iloilo City',
    'Kabankalan City',
    'La Carlota City',
    'Negros Occidental',
    'Passi City',
    'Roxas City',
    'Sagay City',
    'Sipalay City',
    'Victorias City',
  ],
  'Region VII': [
    'Bais City',
    'Bayawan City',
    'Bogo City',
    'Bohol',
    'Canlaon City',
    'Carcar City',
    'Cebu',
    'Cebu City',
    'Danao City',
    'Dumaguete City',
    'Guihulngan City',
    'Lapu-Lapu City',
    'Mandaue City',
    'Naga City',
    'Negros Oriental',
    'Siquijor',
    'Tagbilaran City',
    'Talisay City',
    'Tanjay City',
    'Toledo City',
  ],
  'Region VIII': [
    'Baybay City',
    'Biliran',
    'Borongan City',
    'Calbayog City',
    'Catbalogan City',
    'Eastern Samar',
    'Leyte',
    'Maasin City',
    'Northern Samar',
    'Ormoc City',
    'Samar (Western Samar)',
    'Southern Leyte',
    'Tacloban City',
  ],
  'Region IX': [
    'Zamboanga Del Norte',
    'Zamboanga Del Sur',
    'Zamboanga Sibugay',
    'Dapitan City',
    'Dipolog City',
    'Isabela City',
    'Pagadian City',
    'Zamboanga City',
  ],
  'Region X': [
    'Bukidnon',
    'Cagayan de Oro City',
    'Camiguin',
    'El Salvador City',
    'Gingoog City',
    'Iligan City',
    'Lanao Del Norte',
    'Malaybalay City',
    'Misamis Occidental',
    'Misamis Oriental',
    'Oroquieta City',
    'Ozamis City',
    'Tangub City',
    'Valencia City',
  ],
  'Region XI': [
    'Davao City',
    'Davao de Oro',
    'Davao del Norte',
    'Davao Del Sur',
    'Davao Occidental',
    'Davao Oriental',
    'Digos City',
    'Mati City',
    'Panabo City',
    'Samal City',
    'Tagum City',
  ],
  'Region XII': [
    'Cotabato',
    'General Santos City',
    'Kidapawan City',
    'Koronadal City',
    'Saranggani',
    'South Cotabato',
    'Sultan Kudarat',
    'Tacurong City',
  ],
  'Region XIII': [
    'Agusan Del Norte',
    'Agusan Del Sur',
    'Bayugan City',
    'Bislig City',
    'Butuan City',
    'Cabadbaran City',
    'Dinagat Islands',
    'Siargao',
    'Surigao City',
    'Surigao Del Norte',
    'Surigao del Sur',
    'Tandag City',
  ],
  'BARMM': [
    'Lanao del Sur I',
    'Lanao del Sur II',
    'Maguindanao II',
    'Sulu',
    'Tawi-Tawi',
    'Basilan',
    'Marawi City',
    'Lamitan City',
    'Cotabato City',
  ],
};

export const MOCK_SEED_EMAILS = [
  'adriel@example.org',
  'janel@example.org',
  'gem@example.org',
  'marti@example.org',
  'christine@example.org',
  'admin@starlink.local',
];
