
import { getCurrentUser, hasAcceptedLatestTerms } from '@/lib/auth';
import { REGION_DISPLAY_NAMES } from '@/lib/constants';
import { getRegionalInsightsDashboard } from '@/lib/regional-insights';

export const dynamic = 'force-dynamic';

function round(value: number, decimals = 1) {
  const factor = 10 ** decimals;
  return Math.round(value * factor) / factor;
}

function timeStampForFile() {
  const now = new Date();
  const year = now.getFullYear();
  const month = `${now.getMonth() + 1}`.padStart(2, '0');
  const day = `${now.getDate()}`.padStart(2, '0');
  return `${year}${month}${day}`;
}

function formatDate(date: Date) {
  return date.toLocaleDateString('en-PH', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export async function GET() {
  const user = await getCurrentUser();

  if (!user) {
    return new Response('Authentication required.', { status: 401 });
  }

  if (!hasAcceptedLatestTerms(user)) {
    return new Response('Terms acceptance required.', { status: 403 });
  }

  if (user.role !== 'admin') {
    return new Response('Admin access required.', { status: 403 });
  }

  const insights = await getRegionalInsightsDashboard();

  // Dynamically import jsPDF (ESM-compatible in Node.js runtime)
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const now = new Date();

  /* ── Page 1: Cover + National Summary ──────── */
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('STAR-LINK', 20, 30);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('Regional Teacher Profile Report', 20, 40);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${formatDate(now)}`, 20, 50);
  doc.text(`Generated by: ${user.full_name ?? 'Admin'}`, 20, 56);
  doc.setTextColor(0, 0, 0);

  // National summary
  const totalTeachers = insights.needsSegmentation.reduce((sum, r) => sum + r.totalTeachers, 0);
  const regionsWithData = insights.needsSegmentation.filter((r) => r.totalTeachers > 0).length;
  const avgStarAccess = totalTeachers > 0
    ? round(insights.topPriorityRegions.reduce((sum, r) => sum + r.starAccessRate * r.teacherCount, 0) / totalTeachers)
    : 0;
  const underservedDivisions = insights.underservedAreas.length;
  const avgCompleteness = insights.freshnessIndicators.length > 0
    ? round(insights.freshnessIndicators.reduce((sum, r) => sum + r.completenessPercentage, 0) / insights.freshnessIndicators.length)
    : 0;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('National Summary', 20, 72);

  autoTable(doc, {
    startY: 76,
    margin: { left: 20 },
    head: [['Metric', 'Value']],
    body: [
      ['Total Teachers Profiled', `${totalTeachers}`],
      ['Regions with Data', `${regionsWithData} / ${insights.needsSegmentation.length}`],
      ['National STAR Access Rate', `${avgStarAccess}%`],
      ['Underserved Divisions Flagged', `${underservedDivisions}`],
      ['Average Data Completeness', `${avgCompleteness}%`],
      ['Research-Consented Teachers', `${insights.anonymizedResearchSummary.totalConsentedTeachers}`],
      ['Anonymized Dataset Rows', `${insights.anonymizedResearchSummary.anonymizedDatasetRows}`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [29, 79, 145], fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } },
  });

  /* ── Page 2: Regional Breakdown ────────────── */
  doc.addPage();
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Regional Breakdown', 20, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Teacher composition, STAR access, and priority indicators per region.', 20, 27);

  const coverageByRegion = new Map(insights.coverageGaps.map((item) => [item.region, item]));

  const regionalRows = insights.topPriorityRegions.map((item) => {
    const seg = insights.needsSegmentation.find((s) => s.region === item.region);
    const cov = coverageByRegion.get(item.region);
    return [
      REGION_DISPLAY_NAMES[item.region] ?? item.region,
      `${item.teacherCount}`,
      `${seg?.newTeachers ?? 0}`,
      `${seg?.midCareerTeachers ?? 0}`,
      `${seg?.veteranTeachers ?? 0}`,
      `${seg?.stemSpecializationGap ?? 0}`,
      `${item.starAccessRate}%`,
      `${item.completenessPercentage}%`,
      `${cov?.coveragePercentage ?? 0}%`,
      `${item.priorityScore}`,
    ];
  });

  autoTable(doc, {
    startY: 32,
    margin: { left: 12, right: 12 },
    head: [['Region', 'Teachers', 'New', 'Mid', 'Vet', 'STEM Gap', 'STAR%', 'Complete%', 'Coverage%', 'Priority']],
    body: regionalRows,
    theme: 'grid',
    headStyles: { fillColor: [29, 79, 145], fontSize: 7.5, fontStyle: 'bold', halign: 'center' },
    bodyStyles: { fontSize: 7.5 },
    columnStyles: {
      0: { cellWidth: 52 },
      1: { halign: 'center' },
      2: { halign: 'center' },
      3: { halign: 'center' },
      4: { halign: 'center' },
      5: { halign: 'center' },
      6: { halign: 'center' },
      7: { halign: 'center' },
      8: { halign: 'center' },
      9: { halign: 'center' },
    },
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 9) {
        const score = parseFloat(data.cell.raw as string);
        if (score >= 40) {
          data.cell.styles.textColor = [185, 28, 28];
          data.cell.styles.fontStyle = 'bold';
        } else if (score >= 20) {
          data.cell.styles.textColor = [180, 120, 0];
        }
      }
    },
  });

  /* ── Page 3: Underserved Areas ─────────────── */
  if (insights.underservedAreas.length > 0) {
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Underserved Area Analysis', 20, 20);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('Division-level areas flagged by the underserved scoring algorithm (threshold >= 35).', 20, 27);

    const underservedRows = insights.underservedAreas.slice(0, 25).map((area) => [
      REGION_DISPLAY_NAMES[area.region] ?? area.region,
      area.division,
      `${area.teacherCount}`,
      `${area.averageExperience} yr`,
      `${area.underservedScore}`,
      area.underservedReasons.join(', '),
    ]);

    autoTable(doc, {
      startY: 32,
      margin: { left: 12, right: 12 },
      head: [['Region', 'Division', 'Teachers', 'Avg Exp', 'Score', 'Reasons']],
      body: underservedRows,
      theme: 'grid',
      headStyles: { fillColor: [185, 28, 28], fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 45 },
        1: { cellWidth: 40 },
        2: { halign: 'center', cellWidth: 18 },
        3: { halign: 'center', cellWidth: 18 },
        4: { halign: 'center', cellWidth: 14 },
      },
      didParseCell(data) {
        if (data.section === 'body' && data.column.index === 4) {
          const score = parseFloat(data.cell.raw as string);
          if (score >= 60) {
            data.cell.styles.textColor = [185, 28, 28];
            data.cell.styles.fontStyle = 'bold';
          }
        }
      },
    });
  }

  /* ── Page 4: Coverage Gaps ─────────────────── */
  doc.addPage();
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Division Coverage Gaps', 20, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Expected vs. covered divisions per region with gap severity classification.', 20, 27);

  const coverageRows = insights.coverageGaps.map((gap) => [
    REGION_DISPLAY_NAMES[gap.region] ?? gap.region,
    `${gap.teacherCount}`,
    `${gap.coveredDivisions} / ${gap.expectedDivisions}`,
    `${gap.coveragePercentage}%`,
    gap.gapLevel.toUpperCase(),
    gap.missingDivisions.length > 0 ? gap.missingDivisions.slice(0, 4).join(', ') + (gap.missingDivisions.length > 4 ? ` +${gap.missingDivisions.length - 4} more` : '') : 'None',
  ]);

  autoTable(doc, {
    startY: 32,
    margin: { left: 12, right: 12 },
    head: [['Region', 'Teachers', 'Divisions', 'Coverage', 'Gap Level', 'Missing Divisions']],
    body: coverageRows,
    theme: 'grid',
    headStyles: { fillColor: [29, 79, 145], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { halign: 'center', cellWidth: 18 },
      2: { halign: 'center', cellWidth: 22 },
      3: { halign: 'center', cellWidth: 18 },
      4: { halign: 'center', cellWidth: 18 },
    },
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 4) {
        const level = (data.cell.raw as string).toLowerCase();
        if (level === 'critical') {
          data.cell.styles.textColor = [185, 28, 28];
          data.cell.styles.fontStyle = 'bold';
        } else if (level === 'warning') {
          data.cell.styles.textColor = [180, 120, 0];
        } else {
          data.cell.styles.textColor = [22, 163, 74];
        }
      }
    },
  });

  /* ── Page 5: Program Recommendations ───────── */
  doc.addPage();
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Program Recommendations', 20, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Auto-generated capacity-building recommendations per region based on profiling data.', 20, 27);

  const recRows = insights.programRecommendations.map((rec) => [
    REGION_DISPLAY_NAMES[rec.region] ?? rec.region,
    `${rec.teacherCount}`,
    `${rec.priorityScore}`,
    rec.recommendedPrograms.join('\n'),
    rec.rationale.join('; '),
  ]);

  autoTable(doc, {
    startY: 32,
    margin: { left: 12, right: 12 },
    head: [['Region', 'Teachers', 'Priority', 'Recommended Programs', 'Rationale']],
    body: recRows,
    theme: 'grid',
    headStyles: { fillColor: [63, 68, 140], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5 },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { halign: 'center', cellWidth: 18 },
      2: { halign: 'center', cellWidth: 16 },
      3: { cellWidth: 80 },
    },
  });

  /* ── Footer on all pages ───────────────────── */
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `STAR-LINK Regional Teacher Profile Report • Page ${i} of ${totalPages} • Generated ${formatDate(now)}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' },
    );
    doc.setTextColor(0, 0, 0);
  }

  const pdfBuffer = doc.output('arraybuffer');
  const fileName = `STAR-LINK-Regional-Report-${timeStampForFile()}.pdf`;

  return new Response(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${fileName}"`,
      'Cache-Control': 'private, no-store, max-age=0',
    },
  });
}
